### ISSUE TITLE
Can i add more API's to this library?

### ISSUE THREAD

**Issue by speed650** [ikbale/fmp_python#11]
Hi,
Im learning about python and stock trading, and im using financialmodelingprep as their pricing seems good and they have the API calls that im interested. I came across your project on their website. I notice you only have a few functions in this project. I will be working with more functions on their website (hopefully most of them), i can add more of them to this library if OK.

I am new to GitHub, so i might need some help with how to do pull / commits.

**Comment by ikbale** [comment]
Hello, sorry for the late reply.
I will be soon releasing a new version that contains some fixes so you can go from that for your contribution to the library !

**Comment by speed650** [comment]
Hi
There is a few query sting segments that need to be added, for example
frequency to make some api work

But I learn a few things looking over your code. Notably custom decorators.
I am just learning Python

**Comment by speed650** [comment]
Here are some additional components that are needed.


   - limit
   - period
   - symbol
   - year
   - page
   - query
   - exchange

https://financialmodelingprep.com/api/v3/ratios/AAPL?limit=40
https://financialmodelingprep.com/api/v3/ratios/AAPL?period=quarter
&limit=140
https://financialmodelingprep.com/api/v4/financial-reports-json?symbol=AAPL&
year=2020&period=FY
https://financialmodelingprep.com/api/v4/institutional-ownership/rss_feed?
page=0
https://financialmodelingprep.com/api/v3/search?query=AA&limit=10&
exchange=NASDAQ


  There are some additional ones as well for stock screener and feeds.
