### ISSUE TITLE
return request+'?apikey='+api_key

### ISSUE THREAD

**Issue by Valeeswaran** [ikbale/fmp_python#3]
Getting the following error message.

  File "E:\PyStoxBoard\lib\site-packages\fmp_python\common\fmpdecorator.py", line 20, in deco_function
    return request+'?apikey='+api_key
TypeError: can only concatenate str (not "NoneType") to str

**Comment by Valeeswaran** [comment]
Found the root cause and fixed it. While using in windows environment we have set the environment variable as 
variable=FMP_API_KEY
value=api_key

then only the following function picking up.

class FMPDecorator():

    @classmethod
    def inject_api_key(cls,func):
        @functools.wraps(func)
        def deco_function(*args, **kwargs):
            api_key = os.getenv('FMP_API_KEY')

even though we have used the following code in program
fmp = FMP(api_key='814f49c62c2095e81dbea37ae8015c05')

**Comment by Gtsoun** [comment]
I have the same problem. How exactly did you fix it? I still can't get it to work

**Comment by ikbale** [comment]
> I have the same problem. How exactly did you fix it? I still can't get it to work

Hello ! To fix the problem, you should set your environment variable FMP_API_KEY with you api key. Apparently, There is a bug with the method FMP(api_key= ..) and the fix will be included in the next version :)

**Comment by ikbale** [comment]
> Found the root cause and fixed it. While using in windows environment we have set the environment variable as
> variable=FMP_API_KEY
> value=api_key
> 
> then only the following function picking up.
> 
> class FMPDecorator():
> 
> ```
> @classmethod
> def inject_api_key(cls,func):
>     @functools.wraps(func)
>     def deco_function(*args, **kwargs):
>         api_key = os.getenv('FMP_API_KEY')
> ```
> 
> even though we have used the following code in program
> fmp = FMP(api_key='814f49c62c2095e81dbea37ae8015c05')

As I mentionned below, there is a bug fix of this method that will included in the next version. In the meanwhile, setting the Environment variable should fix the problem !

**Comment by ikbale** [comment]
Issue resolved in 0.1.4
