### ISSUE TITLE
query with multiple tickers

### ISSUE THREAD

**Issue by simpsus** [ikbale/fmp_python#6]
Is there a way to query more than one ticker at once?
when I create a space seperated string like so

`fmp.get_quote(' '.join(tickers))`

I only get a _ as the return ...

Thank you very much!

**Comment by ikbale** [comment]
Hello, 

Did you try `fmp.get_quote(','.join(tickers))` instead ?

**Comment by simpsus** [comment]
Thank you very much! With other endpoints (eg. technical_indicator) I had no luck. Do you know of a way to know for which endpoints this is possible?

**Comment by ikbale** [comment]
aah it's normal, the current version doesn't include the 'technical_indicator'. Read the documentation here https://github.com/ikbale/fmp_python on the fmp_python PiPy page to know which endpoints are currently included !
I'm currently working on a version that includes more endpoints from Financial Modeling Prep API :)

**Comment by simpsus** [comment]
I added the "techical_indicator" to the supported categories so that the request go through, eg.

`https://financialmodelingprep.com/api/v3/technical_indicator/daily/EMR,ICE?type=dema&period=10&apikey=...`

but what I get back is

{'timestamp': '2021-06-07T13:58:09.983+0000',
 'status': 500,
 'error': 'Internal Server Error',
 'message': 'No message available',
 'path': '/api/v3/technical_indicator/daily/EMR,ICE'}

**Comment by ikbale** [comment]
I can not know if the API supports multiple tickers at once for this category, I have access to the same public documentation. However, fmp_python library can only get you data for these categories https://github.com/ikbale/fmp_python#readme.

I will try to include in the next version a way to get multiple tickers for endpoints that does not necessarly support this option :)

**Comment by simpsus** [comment]
very nice. Thx for the insights!
My biggest "pain" point is the API call limit per minute on some plans. So if there was some way to say: Spread out the API calls so that X/minute is not surpassed, that would be very cool.

I close this issue, please feel free to comment.
